#ifndef _DEBUG_UTILS_SETTINGS_H_
#define _DEBUG_UTILS_SETTINGS_H_

//#define RELEASE

#define DEBUG_UNIT_LIST\
    X(d_meteorvb),\
    X(d_s2mmu),\
    X(d_semihost),\
    X(d_gic2_vctrl),\
    X(d_gic2_vcpu_if),\
    \
    X(d_cpu_monitor),\
    X(d_black_hole),\
    \
    X(d_inst),\
    X(d_inst_vm0),\
    X(d_inst_vm1),\
    X(d_inst_vm2),\
    X(d_inst_vm3),\
    X(d_inst_clean),\
    X(d_inst_clean_vm0),\
    X(d_inst_clean_vm1),\
    X(d_inst_clean_vm2),\
    X(d_inst_clean_vm3),\
    X(d_rf_dump),\
    X(d_rf_dump_vm0),\
    X(d_rf_dump_vm1),\
    X(d_rf_dump_vm2),\
    X(d_rf_dump_vm3),\
    \
    X(d_str),\
    X(d_inst_assert),\
    X(d_main),\
    X(d_realviewpb),\
    X(d_gdbstub),\
    X(d_ahb),\
    X(d_ahb_master_if),\
    X(d_ahb_slave_if),\
    X(d_decoder),\
    X(d_tlm_payload_pool),\
    X(d_aaci),\
    X(d_clcd),\
    X(d_dma),\
    X(d_gpio),\
    X(d_gic),\
    X(d_gic_in),\
    X(d_mci),\
    X(d_mpmc),\
    X(d_ps2),\
    X(d_ram),\
    X(d_rom),\
    X(d_rtc),\
    X(d_sci),\
    X(d_ssmc),\
    X(d_ssp),\
    X(d_sysctrl_0),\
    X(d_sysctrl_1),\
    X(d_sig),\
    X(d_timer),\
    X(d_uart),\
    X(d_vic),\
    X(d_watchdog),\
    \
    X(d_armv7a),\
    X(d_armv7a_arch),\
    X(d_armv7a_bank),\
    X(d_armv7a_reg),\
    X(d_armv7a_rf),\
    X(d_armv7a_cp15),\
    X(d_armv7a_bus),\
    X(d_armv7a_cmsa),\
    X(d_armv7a_exception),\
    X(d_armv7a_ex_monitor),\
    X(d_armv7a_misc),\
    X(d_armv7a_sys),\
    X(d_armv7a_vm),\
    X(d_armv7a_vmsa),\
    X(d_armv7a_gdbstub),\
    \
    X(d_armv7a_decode_br),\
    X(d_armv7a_decode_dpimm),\
    X(d_armv7a_decode_dpmisc),\
    X(d_armv7a_decode_dpreg),\
    X(d_armv7a_decode_dpsreg),\
    X(d_armv7a_decode_extrals),\
    X(d_armv7a_decode_extrals_up),\
    X(d_armv7a_decode_hmulmacc),\
    X(d_armv7a_decode_ls),\
    X(d_armv7a_decode_media),\
    X(d_armv7a_decode_misc),\
    X(d_armv7a_decode_misc_mhints),\
    X(d_armv7a_decode_msrhints),\
    X(d_armv7a_decode_mulmacc),\
    X(d_armv7a_decode_pack_satrev),\
    X(d_armv7a_decode_paddsub_s),\
    X(d_armv7a_decode_paddsub_us),\
    X(d_armv7a_decode_sat),\
    X(d_armv7a_decode_smul),\
    X(d_armv7a_decode_svccp),\
    X(d_armv7a_decode_sync),\
    X(d_armv7a_decode_top),\
    X(d_armv7a_decode_uncond),\
    X(d_armv7a_decode_undef),\
    \
    X(d_gic2_dist),\
    X(d_gic2_cpu_if),\
    \
    X(d_inst_dpmisc),\
    X(DEBUG_UNIT_COUNT)
#endif
